version: "3.9"

services:
  app:
    image: docker.io/miatrika05/ticklab:${IMAGE_TAG}
    container_name: ticklab_app
    restart: unless-stopped
    working_dir: /var/www/html
    env_file:
      - ./app_code/.env
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ticklab
      DB_USERNAME: root
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./app_code:/var/www/html
      - vendor_data:/var/www/html/vendor
    depends_on:
      - db
    networks:
      - ticklab_net
    dns:
      - 8.8.8.8
      - 1.1.1.1
    healthcheck:
      test: ["CMD-SHELL", "pgrep php-fpm || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  nginx:
    image: docker.io/miatrika05/ticklab-nginx:${IMAGE_TAG}
    container_name: ticklab_nginx
    restart: unless-stopped
    ports:
      - "${HOST_HTTP_PORT:-8080}:80"
      - "${HOST_HTTPS_PORT:-443}:443"
    volumes:
      - ./app_code:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro   # â† AJOUT SSL
      - /dev/null:/docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
    depends_on:
      - app
    networks:
      - ticklab_net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  db:
    image: mysql:8.0
    container_name: ticklab_db
    restart: unless-stopped
    command: >
      --default-authentication-plugin=mysql_native_password
      --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ticklab
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ticklab_net

volumes:
  db_data:
  vendor_data:

networks:
  ticklab_net:

  
