version: "3.9"

services:
  app:
    image: docker.io/miatrika05/ticklab:${IMAGE_TAG}
    container_name: ticklab_app
    restart: unless-stopped
    working_dir: /var/www/html
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=ticklab
      - DB_USERNAME=root
      - DB_PASSWORD=15182114
    volumes:
      - vendor_data:/var/www/html/vendor
    depends_on:
      - db
    networks:
      - ticklab_net
    dns:
      - 8.8.8.8
      - 1.1.1.1

  nginx:
    image: nginx:alpine
    container_name: ticklab_nginx
    restart: unless-stopped
    ports:
      - "${HOST_HTTP_PORT:-8080}:80"
    volumes:
      - .:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - ticklab_net

  db:
    image: mysql:8.0
    container_name: ticklab_db
    restart: unless-stopped
    command: >
      --default-authentication-plugin=mysql_native_password
      --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: 15182114
      MYSQL_DATABASE: ticklab
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - ticklab_net

volumes:
  db_data:
  vendor_data:

networks:
  ticklab_net:
